books-text
front-end-by-rimantas/44-grupe-portfolio-ewebot pull request #83
Opened 2023-05-22 19:27 UTC by RasikaM

2023-05-22 19:33 UTC, GiedreRag approved these changes

2023-05-22 21:19 UTC, AndriusCa requested changes
h1 needs to be changed.  Capital letters also should be changed to lowercase. (SHOP MY BOOKS, Read My Books etc.)

2023-05-23 07:28 UTC, GiedreRag commented
Pirmas zodis prasideda didziaja raide. Reik visiems vienodai rasyt, per visas section.

2023-05-23 16:47 UTC, GiedreRag approved these changes

2023-05-23 16:55 UTC, AndriusCa approved these changes

2023-05-23 16:56 UTC, GiedreRag approved these changes

2023-05-23 16:56 UTC, TadasRup approved these changes

2023-05-23 16:57 UTC, merged